- name: Install Required CLI tools in Ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - jq
      - gpg
      - curl  # needed to install rust
      - cmake # starship needs this to compile
      - python3-apt
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Required CLI tools in MacOSX
  become: true
  community.general.homebrew:
    name:
      - jq
    state: present
  when: ansible_distribution == "MacOSX"

- name: Update Pacman Mirrors
  become: true
  ansible.builtin.shell: pacman-mirrors -c United_States 
  when: ansible_distribution == "Archlinux"

- name: Install Required CLI tools in Arch/Manjaro
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - jq
      - gcc
      - cmake
      - make
    state: present
  when: ansible_distribution == "Archlinux"
