- name: check if cargo is installed
  shell: which cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

- name: Install rust programs
  shell: ". {{ ansible_env.CARGO_HOME }}/env && cargo install --locked {{ cargo_programs }}"
