---
- name: Install zsh in MacOs
  become: true
  community.general.homebrew:
    name:
      - zsh
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install zsh in Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - zsh
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh in Manjaro
  become: true
  ansible.builtin.pacman:
    update_cache: true
    name:
      - zsh
    state: present
  when: ansible_distribution == "Archlinux"
