---
- name: Install zsh in MacOs
  become: true
  community.general.homebrew:
    name:
      - zsh
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh in Ubuntu
  become: true
  apt:
    name:
      - zsh
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh in Manjaro
  become: true
  pacman:
    name:
      - zsh
    state: present
  when: ansible_distribution == "Manjaro"
