- name: Install ZSH
  apt:
    name: zsh

- name: Clone zsh-* repos into XDG_DATA_HOME
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/{{ item }}.git'
    dest: "{{ ansible_env.XDG_DATA_HOME }}/zsh/{{ item }}"
    version: master
    update: true
  loop:
    - "zsh-autosuggestions"
    - "zsh-syntax-highlighting"
    - "zsh-completions"

- name: Change user shell to zsh 
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"
