- name: Install ZSH
  apt: name=zsh

- name: Clone zsh-* repos into XDG_DATA_HOME
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/{{ item }}.git'
    dest: "{{ xdg_vars.data_home }}/{{ item }}"
    version: master
    update: true
  loop:
    - "zsh-autosuggestions"
    - "zsh-syntax-highlighting"
    - "zsh-completions"

- name: Change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"
