- name: Install zsh-* repos into XDG_DATA_HOME
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/{{ item }}.git'
    dest: "{{ xdg_dirs.data_home }}/{{ item }}"
  loop:
    - "zsh-autosuggestions"
    - "zsh-syntax-highlighting"
    - "zsh-completions"

- name: Change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "/bin/zsh"
