- name: Ensure core XDG directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_list:
    - '{{ansible_env.XDG_CONFIG_HOME}}'
    - '{{ansible_env.XDG_CACHE_HOME}}'
    - '{{ansible_env.XDG_DATA_HOME}}'
    - '{{ansible_env.XDG_STATE_HOME}}'
  tags: 
  - core

- import_tasks: ssh-personal.yml
  no_log: true
  tags:
    - core
    - vault
    - ssh-personal

- import_tasks: gpg-personal.yml
  no_log: true
  tags:
    - core
    - vault
    - gpg-personal

- import_tasks: ssh-work.yml
  no_log: true
  tags:
    - core
    - vault
    - ssh-work

- import_tasks: gpg-work.yml
  no_log: true
  tags:
    - core
    - vault
    - gpg-work
