- name: Ensure core XDG directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_list:
    - '{{ansible_env.XDG_CONFIG_HOME}}'
    - '{{ansible_env.XDG_CACHE_HOME}}'
    - '{{ansible_env.XDG_DATA_HOME}}'
    - '{{ansible_env.XDG_STATE_HOME}}'
  tags: 
  - core

- import_tasks: ssh-personal.yml
  tags:
    - core
    - vault
    - ssh-personal

- import_tasks: gpg-personal.yml
  tags:
    - core
    - vault
    - gpg-personal

- import_tasks: ssh-work.yml
  tags:
    - core
    - vault
    - ssh-work

- import_tasks: gpg-work.yml
  tags:
    - core
    - vault
    - gpg-work


# - name: add git-core ppa
#   become: true
#   ansible.builtin.apt_repository:
#     repo: ppa:git-core/stable
#     state: present
#     update_cache: false
#   when: ansible_distribution == "Ubuntu"
#   tags: 
#   - core
#   - git-latest
#   - ppa

# - name: update git
#   become: true
#   ansible.builtin.apt:
#     name: git
#     update_cache: true
#     state: latest
#   when: ansible_distribution == "Ubuntu"
#   tags:
#   - core
#   - git-latest
