- include_vars:
    file: vars/personal.yml

- name: Ensure ssh dir exists
  ansible.builtin.file:
    path: '{{ansible_env.HOME}}/.ssh'
    state: directory
    mode: '700'

- name: Copy personal ssh private key to new machine
  ansible.builtin.copy:
    content: '{{ vault_private_ssh_personal }}'
    dest: '{{ansible_env.HOME}}/.ssh/id_ed25519_personal'
    mode: '600'

- name: Copy personal ssh public key to new machine
  ansible.builtin.copy:
    content: '{{ vault_public_ssh_personal }}'
    dest: '{{ansible_env.HOME}}/.ssh/id_ed25519_personal.pub'
    mode: '644'

