- include_vars:
    file: vars/work.yml

- name: Ensure ssh dir exists
  ansible.builtin.file:
    path: '{{ansible_env.HOME}}/.ssh'
    state: directory
    mode: '700'

- name: Copy work ssh private key to new machine
  ansible.builtin.copy:
    content: '{{ vault_private_ssh_work }}'
    dest: '{{ansible_env.HOME}}/.ssh/id_ed25519_work'
    mode: '600'

- name: Copy work ssh public key to new machine
  ansible.builtin.copy:
    content: '{{ vault_public_ssh_work }}'
    dest: '{{ansible_env.HOME}}/.ssh/id_ed25519_work.pub'
    mode: '644'
